import {
  faHome,
  faBook,
  faSearch,
  faMusic,
  faCog,
  faStar as faStarFilled,
  faRandom,
  faQuestion,
  faInfo,
  faPowerOff,
  faCaretLeft,
  faCaretRight,
  faVolumeXmark,
  faVolumeHigh,
  faPaperPlane,
  faMicrophone,
} from "@fortawesome/free-solid-svg-icons";
import { faStar as faStarEmpty } from "@fortawesome/free-regular-svg-icons";

export const icons = {
  faHome,
  faBook,
  faSearch,
  faMusic,
  faCog,
  faStarFilled,
  faStarEmpty,
  faRandom,
  faQuestion,
  faInfo,
  faPowerOff,
  faCaretLeft,
  faCaretRight,
  faVolumeXmark,
  faVolumeHigh,
  faPaperPlane,
  faMicrophone,
};
